input{
    jdbc{
        jdbc_connection_string => "jdbc:postgresql://host.docker.internal:5432/test_db"
        jdbc_user => "postgress"
        jdbc_password => "Admin"
        jdbc_driver_class => "org.postgresql.Driver"
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql.jar"
        statement => "SELECT id, name, quantity FROM products"
        schedule => "* * * * * *"
        use_column_value => true
        tracking_column => "updated_at"
        tracking_column_type => "timestamp"
        type => "product"
    }
    jdbc{
        jdbc_connection_string => "jdbc:postgresql://host.docker.internal:5432/test_db"
        jdbc_user => "postgress"
        jdbc_password => "Admin"
        jdbc_driver_class => "org.postgresql.Driver"
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql.jar"
        statement => "SELECT id, name, description FROM category"
        schedule => "* * * * * *"
        use_column_value => true
        tracking_column => "updated_at"
        tracking_column_type => "timestamp"
        type => "category" 
    } 
}
filter{
        mutate {
            remove_field=> ["@version","@timestamp"]
        }
}
output{
        if [type] == "product" {
            elasticsearch{
                hosts => ["http://elasticsearch:9200"]
                index => "products_index"
                document_id => "%{id}"
            }
        }
        if [type] == "category" {
            elasticsearch {
                hosts => ["http://elasticsearch:9200"]
                index => "category_index"
                document_id => "%{id}"
            }
        }
    stdout {codec => rubydebug}
}
