services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
        container_name: elasticsearch
        environment:
          - discovery.type=single-node
          - xpack.security.enabled=false
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
          - "9200:9200"
        healthcheck:
          test: ["CMD","curl","-f","http://localhost:9200"]
          interval: 30s
          timeout: 40s
          retries : 3
    kibana:
      image: docker.elastic.co/kibana/kibana:9.2.3
      container_name: kibana_cn
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - XPACK_SECURITY_ENABLED=false
      ports:
        - "5601:5601"
      depends_on:
        elasticsearch:
            condition: service_healthy
    logstash:
      image: docker.elastic.co/logstash/logstash:9.2.3
      container_name: logstash
      volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/drivers/postgresql-42.7.9.jar:/usr/share/logstash/logstash-core/lib/jars/postgresql.jar
      depends_on:
        elasticsearch:
          condition: service_healthy