apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasets
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: nginx
          image: nginx/latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "1"
          ports:
            - containerPort: 80

