kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: cm9vdAo= #this is the base64 encoded value. Encoding it for make it compatiable for system cause the file is being converted into binary so it is easy for system to read it
